/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba;

import java.util.*;
import javax.swing.*;

/**
 *
 * @author kangaru
 */
public class ModificarVideo1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarVideo1
     */
    private static String nick;
    private static String nomVideo;
    
    public ModificarVideo1(String nick, String nomVideo) {
        this.nick = nick;
        this.nomVideo = nomVideo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtURL = new javax.swing.JTextField();
        txtDur = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        dia = new javax.swing.JComboBox<>();
        mes = new javax.swing.JComboBox<>();
        anio = new javax.swing.JComboBox<>();
        cat = new javax.swing.JComboBox<>();
        priv = new javax.swing.JComboBox<>();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("Titulo");

        jLabel2.setText("URL");

        jLabel3.setText("Duracion");

        jLabel4.setText("Descripcion");

        jLabel5.setText("Fecha de publicacion");

        jLabel6.setText("Categoria");

        jLabel7.setText("Privacidad");

        Sistema sistema = prueba.Inicio.sistema;
        DtVideo data = sistema.getDataVideo(this.nomVideo, this.nick);
        txtTitulo.setText(txtTitulo.getText() + data.getNomVideo());

        Sistema sistema1 = prueba.Inicio.sistema;
        DtVideo data1 = sistema1.getDataVideo(this.nomVideo, this.nick);
        txtURL.setText(txtURL.getText() + data1.getURL());

        Sistema sistema2 = prueba.Inicio.sistema;
        DtVideo data2 = sistema2.getDataVideo(this.nomVideo, this.nick);
        txtDur.setText(txtDur.getText() + data2.getDuracion());

        Sistema sistema3 = prueba.Inicio.sistema;
        DtVideo data3 = sistema3.getDataVideo(this.nomVideo, this.nick);
        txtDesc.setText(txtDesc.getText() + data3.getDescripcion());

        dia.setModel(new DefaultComboBoxModel<Integer>());
        Sistema sis = prueba.Inicio.sistema;
        DtVideo dt = sis.getDataVideo(this.nomVideo, this.nick);
        Fecha f = dt.getFecha();
        int n1 = 1;
        int in = 0;
        int item;
        while(n1 <= 31){
            dia.addItem(n1);
            n1 = n1+1;
            item = dia.getItemAt(in);
            if(f.getDia() == item){
                dia.setSelectedIndex(in);
            }
            in = in+1;
        }

        mes.setModel(new DefaultComboBoxModel<Integer>());
        Sistema sis1 = prueba.Inicio.sistema;
        DtVideo dt1 = sis1.getDataVideo(this.nomVideo, this.nick);
        Fecha f1 = dt1.getFecha();
        int n2 = 1;
        int in1 = 0;
        int item1;
        while(n2 <= 12){
            mes.addItem(n2);
            n2 = n2+1;
            item1 = mes.getItemAt(in1);
            if(f1.getMes() == item1){
                mes.setSelectedIndex(in1);
            }
            in1 = in1+1;
        }

        anio.setModel(new DefaultComboBoxModel<Integer>());
        Sistema sis2 = prueba.Inicio.sistema;
        DtVideo dt2 = sis2.getDataVideo(this.nomVideo, this.nick);
        Fecha f2 = dt2.getFecha();
        int n3 = 1930;
        int in2 = 0;
        int item2;
        while(n3 <= 2019){
            anio.addItem(n3);
            n3 = n3+1;
            item2 = anio.getItemAt(in2);
            if(f2.getAnio() == item2){
                anio.setSelectedIndex(in2);
            }
            in2 = in2 + 1;
        }

        cat.setModel(new DefaultComboBoxModel<String>());
        Collection<DtCategoria> c;
        Sistema s = prueba.Inicio.sistema;
        c = s.ListaCategorias();
        Iterator<DtCategoria> it = c.iterator();
        String item4;
        int numero = 0;
        cat.addItem("Sin cateogria");
        cat.setSelectedItem("Sin cateogria");
        while(it.hasNext()){
            DtCategoria cat1 = it.next();
            cat.addItem(cat1.getCategoria());
            while(numero < cat.getItemCount()){
                item4 = cat.getItemAt(numero);
                if(cat1.getCategoria().equalsIgnoreCase(item4))
                cat.setSelectedIndex(numero);
                numero = numero + 1;
            }
        }

        priv.setModel(new DefaultComboBoxModel<String>());
        priv.addItem("Privado");
        priv.addItem("Publico");
        Sistema sis3 = prueba.Inicio.sistema;
        DtVideo dt3 = sis3.getDataVideo(this.nomVideo, this.nick);
        String item3;
        int num = 0;
        String privado;
        if(dt3.getPrivado() == true)
        privado = "Privado";

        else
        privado = "Publico";

        while(num < priv.getItemCount()){
            item3 = priv.getItemAt(num);
            if(item3.equalsIgnoreCase(privado)){
                priv.setSelectedIndex(num);
            }
            num = num + 1;
        }

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("Datos Video");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(102, 102, 102))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Aceptar)
                                        .addComponent(jLabel5))
                                    .addGap(36, 36, 36)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(157, 157, 157)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1))
                            .addGap(121, 121, 121)))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Cancelar)
                        .addGap(113, 125, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDur, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(priv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        Sistema s = prueba.Inicio.sistema;
        DtVideo dt = s.getDataVideo(this.nomVideo,this.nick);
        
        if(!dt.getNomVideo().equalsIgnoreCase(txtTitulo.getText())){
            s.ModificarNomVideo(this.nick, this.nomVideo, txtTitulo.getText());
            this.nomVideo = txtTitulo.getText();
        }
        
        Fecha f = dt.getFecha();
        boolean priv1;
        if(priv.getSelectedItem().toString().equalsIgnoreCase("Publico"))
            priv1 = false;
        else
            priv1 = true;
        
        if(!dt.getURL().equalsIgnoreCase(txtURL.getText()))
            s.ModificarURLVideo(this.nick, this.nomVideo, txtURL.getText());
        
        if(!dt.getDuracion().equalsIgnoreCase(txtDur.getText()))
            s.ModificarDurVideo(this.nick, this.nomVideo, txtDur.getText());
        
        if(!dt.getDescripcion().equalsIgnoreCase(txtDesc.getText()))
            s.ModificarDescVideo(this.nick, this.nomVideo, txtDesc.getText());
        
        if(f.getDia() != dia.getItemAt(dia.getSelectedIndex()) && f.getMes() != mes.getItemAt(mes.getSelectedIndex()) && f.getAnio() != anio.getItemAt(anio.getSelectedIndex())){
            Fecha f2 = new Fecha(dia.getItemAt(dia.getSelectedIndex()),mes.getItemAt(mes.getSelectedIndex()),anio.getItemAt(anio.getSelectedIndex()));
            s.ModificarFechaVideo(this.nick, this.nomVideo, f2);
        }
        
        if(dt.getPrivado() != priv1)
            s.ModificarPrivVideo(this.nick, this.nomVideo, priv1);
        
        if(dt.getCategoria() != null){
            if(!dt.getCategoria().equalsIgnoreCase(cat.getItemAt(cat.getSelectedIndex())) && !cat.getItemAt(cat.getSelectedIndex()).equalsIgnoreCase("Sin categoria"))
                s.ModificarCatVideo(this.nick, this.nomVideo, cat.getItemAt(cat.getSelectedIndex()));
        }
        else{
            if(!cat.getItemAt(cat.getSelectedIndex()).equalsIgnoreCase("Sin categoria"))
                s.ModificarCatVideo(this.nick, this.nomVideo, cat.getItemAt(cat.getSelectedIndex()));
        }
        
        this.dispose();
    }//GEN-LAST:event_AceptarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox<Integer> anio;
    private javax.swing.JComboBox<String> cat;
    private javax.swing.JComboBox<Integer> dia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<Integer> mes;
    private javax.swing.JComboBox<String> priv;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtDur;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
