/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Entidades.uytube;

/**
 *
 * @author kangaru
 */
public class DatosVideo extends javax.swing.JFrame {

    /**
     * Creates new form DatosVideo
     */
    private static String nick;
    private static String nomVideo;
    
    public DatosVideo(String nick,String nomVideo) {
        this.nick = nick;
        this.nomVideo = nomVideo;
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Comentarios = new javax.swing.JButton();
        Valoraciones = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        txtTitulo = new javax.swing.JLabel();
        txtURL = new javax.swing.JLabel();
        txtdur = new javax.swing.JLabel();
        txtDesc = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        txtCat = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Comentarios.setText("Comentarios");
        Comentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComentariosActionPerformed(evt);
            }
        });

        Valoraciones.setText("Valoraciones");
        Valoraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValoracionesActionPerformed(evt);
            }
        });

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        txtTitulo.setText("");
        Sistema s = Entidades.uytube.Inicio.sistema;
        DtVideo v = s.getDataVideo(this.nomVideo, this.nick);
        txtTitulo.setText(txtTitulo.getText() + "Titulo: " + v.getNomVideo());

        txtURL.setText("");
        Sistema s1 = Entidades.uytube.Inicio.sistema;
        DtVideo v1 = s1.getDataVideo(this.nomVideo,this.nick);
        txtURL.setText(txtURL.getText() + "URL: " + v1.getURL());

        txtdur.setText("");
        Sistema sistema = Entidades.uytube.Inicio.sistema;
        DtVideo video = sistema.getDataVideo(nomVideo, nick);
        txtdur.setText(txtdur.getText() + "Duracion: " + video.getDuracion());

        txtDesc.setText("");
        Sistema s3 = Entidades.uytube.Inicio.sistema;
        DtVideo v3 = s3.getDataVideo(this.nomVideo, this.nick);
        txtDesc.setText(txtDesc.getText() + "Descripcion: " + v3.getDescripcion());

        txtFecha.setText("");
        Sistema s4 = Entidades.uytube.Inicio.sistema;
        DtVideo v4 = s4.getDataVideo(this.nomVideo, this.nick);
        Fecha f = v4.getFecha();
        txtFecha.setText(txtFecha.getText() + "Fecha de publicacion: " + f.getDia() + "/" + f.getMes() + "/" + f.getAnio());

        txtCat.setText("");
        Sistema s5 = Entidades.uytube.Inicio.sistema;
        DtVideo v5 = s5.getDataVideo(this.nomVideo, this.nick);
        if(v5.getCategoria() != null)
        txtCat.setText(txtCat.getText() + "Categoria: " + v5.getCategoria());
        else
        txtCat.setText(txtCat.getText() + "Categoria: Sin Categoria");

        jLabel1.setText("Datos de Video");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(txtDesc)
                            .addComponent(txtTitulo)
                            .addComponent(txtURL))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Volver)
                            .addComponent(Valoraciones)
                            .addComponent(Comentarios)
                            .addComponent(txtCat)
                            .addComponent(txtFecha)
                            .addComponent(txtdur))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(txtTitulo)
                .addGap(18, 18, 18)
                .addComponent(txtURL)
                .addGap(18, 18, 18)
                .addComponent(txtdur)
                .addGap(18, 18, 18)
                .addComponent(txtDesc)
                .addGap(18, 18, 18)
                .addComponent(txtFecha)
                .addGap(18, 18, 18)
                .addComponent(txtCat)
                .addGap(18, 18, 18)
                .addComponent(Comentarios)
                .addGap(18, 18, 18)
                .addComponent(Valoraciones)
                .addGap(18, 18, 18)
                .addComponent(Volver)
                .addGap(42, 42, 42)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComentariosActionPerformed
        ListaComentarios c = new ListaComentarios();
        c.setVisible(true);
    }//GEN-LAST:event_ComentariosActionPerformed

    private void ValoracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValoracionesActionPerformed
        Valoraciones v = new Valoraciones();
        v.setVisible(true);
    }//GEN-LAST:event_ValoracionesActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosVideo(nick,nomVideo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comentarios;
    private javax.swing.JButton Valoraciones;
    private javax.swing.JButton Volver;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtCat;
    private javax.swing.JLabel txtDesc;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtURL;
    private javax.swing.JLabel txtdur;
    // End of variables declaration//GEN-END:variables
}
