/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Entidades.uytube;

import java.util.*;
import javax.swing.*;

/**
 *
 * @author kangaru
 */
public class ModUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModUsuario
     */
    public ModUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        txtnomC = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtape = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnick = new javax.swing.JLabel();
        txtmail = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        priva = new javax.swing.JComboBox<>();
        dia = new javax.swing.JComboBox<>();
        mes = new javax.swing.JComboBox<>();
        anio = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel11.setText("Nombre:");

        Sistema s7 = Entidades.uytube.Inicio.sistema;
        String nick7 = Entidades.uytube.ListaUsr2.jList1.getSelectedValue();

        DtUsuario data7 = s7.getDataUsuario(nick7);
        DtCanal cc1 = data7.getDataCanal();
        txtnomC.setText(txtnomC.getText() + cc1.getNombre());

        jLabel12.setText("Listas de Reproduccion");

        jLabel7.setText("Datos del Usuario");

        jLabel8.setText("Canal");

        jLabel6.setText("Descripcion:");

        Sistema s6 = Entidades.uytube.Inicio.sistema;
        String nick6 = Entidades.uytube.ListaUsr2.jList1.getSelectedValue();
        DtUsuario data6 = s6.getDataUsuario(nick6);
        DtCanal cc = data6.getDataCanal();
        txtdescripcion.setText(txtdescripcion.getText() + cc.getDescripcion());
        txtdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcionActionPerformed(evt);
            }
        });

        jList1.setModel(new DefaultListModel<String>());
        Sistema s = Entidades.uytube.Inicio.sistema;
        String nick5 = Entidades.uytube.ListaUsr2.jList1.getSelectedValue();
        DtUsuario data = s.getDataUsuario(nick5);
        Collection<DtVideo> c = data.getDtVideos();
        Iterator<DtVideo> it = c.iterator();
        while(it.hasNext()){
            DtVideo v = it.next();
            ((DefaultListModel)jList1.getModel()).addElement(v.getNomVideo());
        }
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Nickname:");

        jLabel4.setText("Correo Electronico:");

        jLabel5.setText("Fecha Nacimiento:");

        Sistema s1 = Entidades.uytube.Inicio.sistema;
        String nick = Entidades.uytube.ListaUsr2.jList1.getSelectedValue();
        DtUsuario data1 = s1.getDataUsuario(nick);
        txtnom.setText(txtnom.getText() + data1.getNombre());

        Sistema s2 = Entidades.uytube.Inicio.sistema;
        String nick1 = Entidades.uytube.ListaUsr2.jList1.getSelectedValue();
        DtUsuario data2 = s2.getDataUsuario(nick1);
        txtape.setText(txtape.getText() + data2.getApellido());

        jLabel9.setText("Videos");

        jLabel10.setText("Imagen:");

        Sistema s8 = Entidades.uytube.Inicio.sistema;
        String nick2 = Entidades.uytube.ListaUsr2.jList1.getSelectedValue();
        DtUsuario data3 = s2.getDataUsuario(nick2);
        txtnick.setText(txtnick.getText() + data3.getNick());

        Sistema s9 = Entidades.uytube.Inicio.sistema;
        String nick4 = Entidades.uytube.ListaUsr2.jList1.getSelectedValue();
        DtUsuario dataa = s2.getDataUsuario(nick4);
        txtmail.setText(txtmail.getText() + dataa.getCorreo());

        jList2.setModel(new DefaultListModel<String>());
        Sistema ss = Entidades.uytube.Inicio.sistema;
        String nickk = Entidades.uytube.ListaUsr2.jList1.getSelectedValue();
        Collection<DtLR> cc2 = ss.ListaListaReproducion(nickk);
        Iterator<DtLR> itt = cc2.iterator();
        while(itt.hasNext()){
            DtLR vv = itt.next();
            ((DefaultListModel)jList2.getModel()).addElement(vv.getNombre());
        }
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        priva.setModel(new javax.swing.DefaultComboBoxModel<String>());
        priva.addItem("Privado");
        priva.addItem("Publico");
        Sistema sis3 = Entidades.uytube.Inicio.sistema;
        DtUsuario dt3 = sis3.getDataUsuario(txtnick.getText());
        DtCanal can = dt3.getDataCanal();
        String item3;
        int num = 0;
        String privado;
        if(can.getPrivado() == true){
            privado = "Privado";
        }
        else{
            privado = "Publico";
        }
        while(num < priva.getItemCount()){
            item3 = priva.getItemAt(num);
            if(item3.equalsIgnoreCase(privado)){
                priva.setSelectedIndex(num);
            }
            num = num + 1;
        }

        dia.setModel(new DefaultComboBoxModel<Integer>());
        Sistema sis = Entidades.uytube.Inicio.sistema;
        DtUsuario dt = s.getDataUsuario(txtnick.getText());
        Fecha f = dt.getFecha();
        int n1 = 1;
        int in = 0;
        int item;
        while(n1 <= 31){
            dia.addItem(n1);
            n1 = n1+1;
            item = dia.getItemAt(in);
            if(f.getDia() == item){
                dia.setSelectedIndex(in);
            }
            in = in+1;
        }

        mes.setModel(new javax.swing.DefaultComboBoxModel<Integer>());
        Sistema sis2 = Entidades.uytube.Inicio.sistema;
        DtUsuario dt2 = s.getDataUsuario(txtnick.getText());
        Fecha f2 = dt2.getFecha();
        int n12 = 1;
        int in2 = 0;
        int item2;
        while(n12 <= 12){
            mes.addItem(n12);
            n12 = n12+1;
            item2 = mes.getItemAt(in2);
            if(f2.getMes() == item2){
                mes.setSelectedIndex(in2);
            }
            in2 = in2+1;
        }

        anio.setModel(new javax.swing.DefaultComboBoxModel<Integer>());
        Sistema sis22 = Entidades.uytube.Inicio.sistema;
        DtUsuario dt22 = s.getDataUsuario(txtnick.getText());
        Fecha f22 = dt22.getFecha();
        int n122 = 1930;
        int in22 = 0;
        int item22;
        while(n122 <= 2019){
            anio.addItem(n122);
            n122 = n122+1;
            item22 = anio.getItemAt(in22);
            if(f2.getAnio() == item22){
                anio.setSelectedIndex(in22);
            }
            in22 = in22+1;
        }

        jLabel13.setText("Privacidad:");

        jButton1.setText("Cambiar Imagen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(215, 215, 215))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtmail))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtnick)
                                        .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(156, 156, 156)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtnomC, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(priva, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel9)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jLabel12)
                                    .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Aceptar)
                        .addGap(32, 32, 32)
                        .addComponent(Cancelar)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtnomC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnick))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtmail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(priva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Cancelar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcionActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

    }//GEN-LAST:event_jList1MouseClicked

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1ValueChanged

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList2MouseClicked

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        Sistema s = Entidades.uytube.Inicio.sistema;
        DtUsuario dt = s.getDataUsuario(txtnick.getText());
        DtCanal dtc = s.getDataCanal(txtnick.getText());
        Fecha f = dt.getFecha();
        boolean priv;
        if(priva.getSelectedItem().toString().equalsIgnoreCase("Publico"))
            priv = false;
        else
            priv = true;
        if(!dt.getNombre().equalsIgnoreCase(txtnom.getText()))
            s.ModificarNombreU(txtnick.getText(), txtnom.getText());
        
        if(!dt.getApellido().equalsIgnoreCase(txtape.getText()))
            s.ModificarApellidoU(txtnick.getText(), txtape.getText());
           
        if(f.getDia() != dia.getItemAt(dia.getSelectedIndex()) && f.getMes() != mes.getItemAt(mes.getSelectedIndex()) && f.getAnio() != anio.getItemAt(anio.getSelectedIndex())){
            Fecha f2 = new Fecha(dia.getItemAt(dia.getSelectedIndex()),mes.getItemAt(mes.getSelectedIndex()),anio.getItemAt(anio.getSelectedIndex()));
            s.ModificarFechaU(txtnick.getText(),f2);
        }
            
        if(!dtc.getNombre().equalsIgnoreCase(txtnomC.getText()))
            s.ModificarNomC(txtnick.getText(),txtnomC.getText());
        
        if(!dtc.getDescripcion().equalsIgnoreCase(txtdescripcion.getText()))
            s.ModificarDescC(txtnick.getText(), txtdescripcion.getText());
        
        if(dtc.getPrivado() != priv)
            s.ModificarPrivC(txtnick.getText(), priv);
        
        this.dispose();
    }//GEN-LAST:event_AceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SeleccionarImagen sel = new SeleccionarImagen();
        sel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JComboBox<Integer> anio;
    private javax.swing.JComboBox<Integer> dia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<Integer> mes;
    private javax.swing.JComboBox<String> priva;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JLabel txtmail;
    private javax.swing.JLabel txtnick;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtnomC;
    // End of variables declaration//GEN-END:variables
}
