/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Entidades.uytube;
import java.awt.*;
import java.util.*;
import javax.swing.*;
/**
 *
 * @author kangaru
 */
public class MostrarDataUsr extends javax.swing.JInternalFrame {

    /**
     * Creates new form MostrarDataUsr2
     */
    
    private static String nick;
    public MostrarDataUsr(String nick) {
        this.nick = nick;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Volver = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnomC = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtnom = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        txtape = new javax.swing.JLabel();
        txtnick = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtmail = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        Foto = new javax.swing.JLabel();

        jList4.setModel(new DefaultListModel<String>());
        Sistema s8 = Entidades.uytube.Inicio.sistema;
        Collection<DtUsuario> c8 = s8.ListaSeguidos(this.nick);
        Iterator<DtUsuario> it8 = c8.iterator();
        while(it8.hasNext()){
            DtUsuario v8 = it8.next();
            ((DefaultListModel)jList1.getModel()).addElement(v8.getNick());
        }
        jScrollPane4.setViewportView(jList4);

        jLabel7.setText("Datos del Usuario");

        jLabel8.setText("Canal");

        txtdescripcion.setText("");
        Sistema s6 = Entidades.uytube.Inicio.sistema;
        DtUsuario data6 = s6.getDataUsuario(this.nick);
        DtCanal cc = data6.getDataCanal();
        txtdescripcion.setText(txtdescripcion.getText() + "Descripcion: " + cc.getDescripcion());

        jList1.setModel(new DefaultListModel<String>());
        Sistema s = Entidades.uytube.Inicio.sistema;
        DtUsuario data = s.getDataUsuario(this.nick);
        Collection<DtVideo> c = data.getDtVideos();
        Iterator<DtVideo> it = c.iterator();
        while(it.hasNext()){
            DtVideo v = it.next();
            ((DefaultListModel)jList1.getModel()).addElement(v.getNomVideo());
        }
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        jLabel9.setText("Videos");

        jLabel10.setText("Imagen:");

        txtnomC.setText("");
        Sistema s7 = Entidades.uytube.Inicio.sistema;
        DtUsuario data7 = s7.getDataUsuario(this.nick);
        DtCanal cc1 = data7.getDataCanal();
        txtnomC.setText(txtnomC.getText() + "Nombre: " + cc1.getNombre());

        jLabel12.setText("Listas de Reproduccion");

        txtnom.setText("");
        Sistema s1 = Entidades.uytube.Inicio.sistema;
        DtUsuario data1 = s1.getDataUsuario(this.nick);
        txtnom.setText(txtnom.getText() + "Nombre: " + data1.getNombre());

        jList2.setModel(new DefaultListModel<String>());
        Sistema ss = Entidades.uytube.Inicio.sistema;
        Collection<DtLR> cc2 = ss.ListaListaReproducion(this.nick);
        Iterator<DtLR> itt = cc2.iterator();
        while(itt.hasNext()){
            DtLR vv = itt.next();
            ((DefaultListModel)jList2.getModel()).addElement(vv.getNombre());
        }
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        txtape.setText("");
        Sistema s2 = Entidades.uytube.Inicio.sistema;
        DtUsuario data2 = s2.getDataUsuario(this.nick);
        txtape.setText(txtape.getText() + "Apellido: " + data2.getApellido());

        txtnick.setText("");
        Sistema s3 = Entidades.uytube.Inicio.sistema;
        DtUsuario data3 = s3.getDataUsuario(this.nick);
        txtnick.setText(txtnick.getText() + "Nickname: " + data3.getNick());

        jLabel13.setText("Seguidores");

        txtmail.setText("");
        Sistema s4 = Entidades.uytube.Inicio.sistema;
        DtUsuario data4 = s4.getDataUsuario(this.nick);
        txtmail.setText(txtmail.getText() + "Correo Electronico: " + data4.getCorreo());

        jLabel14.setText("Siguiendo");

        txtfecha.setText("");
        Sistema s5 = Entidades.uytube.Inicio.sistema;
        DtUsuario data5 = s5.getDataUsuario(this.nick);
        Fecha f = data5.getFecha();
        txtfecha.setText(txtfecha.getText() + "Fecha Nacimiento: " + f.getDia() + "/" + f.getMes() + "/" + f.getAnio());

        jList3.setModel(new DefaultListModel<String>());
        Sistema ss2 = Entidades.uytube.Inicio.sistema;
        Collection<DtUsuario> c6 = ss2.ListaSeguidores(this.nick);
        Iterator<DtUsuario> it5 = c6.iterator();
        while(it5.hasNext()){
            DtUsuario u = it5.next();
            ((DefaultListModel)jList1.getModel()).addElement(u.getNick());
        }
        jScrollPane3.setViewportView(jList3);

        String origen = Entidades.uytube.SeleccionarImagen.origen;
        ImageIcon foto = new ImageIcon(new ImageIcon(origen).getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH));
        Foto.setIcon(foto);
        Foto.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtnom)
                                                .addComponent(txtape)
                                                .addComponent(txtnick)
                                                .addComponent(txtmail)
                                                .addComponent(txtfecha)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addGap(40, 40, 40)
                                                    .addComponent(Foto)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(txtdescripcion)
                                                .addComponent(txtnomC)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(22, 22, 22)
                                                    .addComponent(jLabel13)
                                                    .addGap(109, 109, 109)
                                                    .addComponent(jLabel14)))
                                            .addGap(118, 118, 118)
                                            .addComponent(jLabel12)))
                                    .addGap(23, 23, 23)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(138, 138, 138))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Volver)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(27, 27, 27)
                        .addComponent(txtnom)
                        .addGap(18, 18, 18)
                        .addComponent(txtape)
                        .addGap(18, 18, 18)
                        .addComponent(txtnick)
                        .addGap(18, 18, 18)
                        .addComponent(txtmail)
                        .addGap(18, 18, 18)
                        .addComponent(txtfecha)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Foto)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addComponent(txtnomC)
                .addGap(18, 18, 18)
                .addComponent(txtdescripcion)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Volver))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        DatosVideo data = new DatosVideo(nick,jList1.getSelectedValue());
        data.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1ValueChanged

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        ConsultaUsr consulta = new ConsultaUsr();
        consulta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Foto;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel txtape;
    private javax.swing.JLabel txtdescripcion;
    private javax.swing.JLabel txtfecha;
    private javax.swing.JLabel txtmail;
    private javax.swing.JLabel txtnick;
    private javax.swing.JLabel txtnom;
    private javax.swing.JLabel txtnomC;
    // End of variables declaration//GEN-END:variables
}
